name: tpmusau_auth
description: TP Flutter Firebase Authentication
publish_to: 'none' # Ce projet n'est pas destiné à être publié
version: 1.0.0+1

# Définition de l'environnement Dart/Flutter
environment:
  sdk: ">=3.2.0 <4.0.0"

# ...existing code...
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  google_sign_in: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
# ...existing code...
# Configuration Flutter
flutter:
  uses-material-design: true
